# Generated by Django 4.2.11 on 2025-06-29 12:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('courses', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Lesson',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('slug', models.SlugField(max_length=250)),
                ('content', models.TextField(blank=True, null=True)),
                ('video_url', models.URLField(blank=True, help_text='Direct URL to video or embed link.', null=True)),
                ('order', models.PositiveIntegerField(help_text='Order of the lesson within the course.')),
                ('is_preview', models.BooleanField(default=False, help_text='Can this lesson be previewed by non-enrolled users?')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lessons', to='courses.course')),
            ],
            options={
                'ordering': ['order'],
                'unique_together': {('course', 'slug')},
            },
        ),
    ]
