# Generated by Django 4.2.11 on 2025-06-29 12:16

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('Category', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('slug', models.SlugField(max_length=200, unique=True)),
                ('short_description', models.CharField(help_text='A brief overview of the course.', max_length=500)),
                ('description', models.TextField(help_text='Detailed course description, including learning objectives.')),
                ('what_you_will_learn', models.TextField(blank=True, help_text='Comma-separated or bullet points of learning outcomes.', null=True)),
                ('requirements', models.TextField(blank=True, help_text='Prerequisites or materials needed for the course.', null=True)),
                ('target_audience', models.TextField(blank=True, help_text='Who is this course for?', null=True)),
                ('thumbnail', models.ImageField(blank=True, help_text='Thumbnail image for the course listing.', null=True, upload_to='course_thumbnails/')),
                ('promo_video_url', models.URLField(blank=True, help_text='Link to a promotional video for the course.', null=True)),
                ('price', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('is_free', models.BooleanField(default=False)),
                ('is_published', models.BooleanField(default=False, help_text='Set to true to make the course visible to users.')),
                ('level', models.CharField(choices=[('beginner', 'Beginner'), ('intermediate', 'Intermediate'), ('advanced', 'Advanced')], default='beginner', max_length=50)),
                ('duration', models.CharField(blank=True, help_text="E.g., '10 hours', '3 weeks'", max_length=50, null=True)),
                ('total_lectures', models.PositiveIntegerField(default=0)),
                ('average_rating', models.DecimalField(decimal_places=2, default=0.0, max_digits=3, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(5)])),
                ('number_of_reviews', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('category', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='courses', to='Category.category')),
                ('instructor', models.ForeignKey(limit_choices_to={'role__in': ['instructor', 'admin']}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='taught_courses', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
